# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: xcodebuild build test -scheme "jose-swift-Package" -destination "platform=macOS" -resultBundlePath TestResults

    - name: Publish tests results
      uses: kishikawakatsumi/xcresulttool@v1.7.1
      with:
        path: TestResults.xcresult
        show-code-coverage: true
      if: success() || failure()

